### ISSUE TITLE
Exception :ArrayIndexOutOfBoundsException in ParallelTopicModel.sumTypeTopicCounts 

### ISSUE THREAD

**Issue by ThomasDUAN** [juanmirocks/mallet#4]
I run mallet in my training data, but got this Exception:

INFO: overflow in merging on type 1830
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at cc.mallet.topics.ParallelTopicModel.sumTypeTopicCounts(ParallelTopicModel.java:477)
	at cc.mallet.topics.ParallelTopicModel.estimate(ParallelTopicModel.java:849)

**Comment by juanmirocks** [comment]
Thanks @ThomasDUAN -- I'm sorry, at the moment I cannot maintain this software.

Beware that the original mallet library's got several issues as such.

Maybe you find how to fix it?

**Comment by hkarbasi** [comment]
I had a similar issue and I had to look into the code and make some changes to ignore this exception. In my case, the while loop doesn't go out and it is expected to figure out the default value, instead, it writes the error to the output. What I did was not to let `Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException` happen and I checked the index in the while condition as following:

`at cc.mallet.topics.ParallelTopicModel.WorkerRunnable @ 554`

```
index = 0;
while (index < currentTypeTopicCounts.length &&
		currentTypeTopicCounts[index] > 0 &&
	   (currentTypeTopicCounts[index] & topicMask) != newTopic) {
	index++;
	if (index == currentTypeTopicCounts.length) {
		System.err.println("type: " + type + " new topic: " + newTopic);
		for (int k=0; k<currentTypeTopicCounts.length; k++) {
			System.err.print((currentTypeTopicCounts[k] & topicMask) + ":" + 
							 (currentTypeTopicCounts[k] >> topicBits) + " ");
		}
		System.err.println();

	}
}


// index should now be set to the position of the new topic,
//  which may be an empty cell at the end of the list.
if (index == currentTypeTopicCounts.length)
	index--;


```

What I would suggest is to download the code and debug it yourself. :)

**Comment by hkarbasi** [comment]
Recently, I ran **Mallet** with two different datasets (one with 100M and the other one around 1G). Usually, this kind of exception happened with the larger dataset and when I wanted to run in in parallel for larger iteration number like 100 for the larger dataset. It threw **Exception: ArrayIndexOutOfBoundsException** in two different files:  **WorkerRunnable** and **ParallelTopicModel** in different spots. So the thing is when the array reaches the end of the array, it prints “**overflow in merging on type**” to the logger and after that point, the program doesn’t do anything to get out of the situation. I was able to patch these edge cases with index checking before accessing the array. It helps me run it without breaking it but I am not sure how it might change the output anyways and it also keeps printing the same message “**overflow in merging on type** ” as usual but it goes on and doesn’t throw an exception.

I have uploaded the patches on [my Github](https://github.com/hkarbasi/Mallet) and follow the instructions. It has been able to resolve the issues for me as I haven’t seen this break again under different circumstances. If it doesn’t resolve your issues, you should probably download the latest version from [their Github](https://github.com/mimno/Mallet) and debug and build it yourself.

I have also uploaded both datasets; both are four years of data; (1 Jan 2015- 1 Jan 2019), smaller one is StackExchange (DataScience) and the larger one is Reddit (9 DataScience Subreddits) ([datasets](https://drive.google.com/open?id=1q8Dvm-54CgLj-bmVxD6i1hvRT_WhYhpV)) and you would like to play with it.

Good luck.
